# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "The Traceback"
name: "Joel Edem"
email: "Joel.Ametepeh@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Hi and welcome to by blog! This is where I share my thoughts on programming, 
  programming languages and microcontrollers. Follow along for deep dives, tutorials
  and the occasional random idea. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joel-edem.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: immortal-mind.bsky.social
github_username:  Joel-Edem
repository: "Joel-Edem/Joel-Edem"
masthead_title: "The Traceback"

logo: "/assets/media/imgs/pp.jpg"

include: ["_pages"]
# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


locale: "en-US"

plugins:
  - jekyll-feed


  
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: ""
      type: blog
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

atom_feed:
  hide: true
 

author:
  name     : "Joel Edem"
  avatar   : "/assets/media/imgs/pp.jpg"
  bio      : "Hi, I'm not notable"
 # location : "Accra, Ghana"
  links:
  - label: "Email"
    icon: "fas fa-fw fa-envelope-square"
    url: "mailto:JoelAmetepeh@gmail.com"
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/Joel-Edem"
  - label: "Youtube"
    icon: "fab fa-fw fa-youtube"
    url: "https://www.youtube.com/@thetraceback"
  - label: "@immortal-mind.bsky.social"
    icon: "fab fa-fw fa-bluesky"
    url: "https://bsky.app/profile/immortal-mind.bsky.social"


footer:
  links:
    - label: "@immortal-mind.bsky.social"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/immortal-mind.bsky.social"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Joel-Edem"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@thetraceback"


collections:
  blog:
    output: true
    permalink: /:collection/:path/
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#`
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
